# Generated by Django 5.1.3 on 2025-09-12 04:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='reviews',
            field=models.IntegerField(default=0),
        ),
    ]
