# Generated by Django 5.1.3 on 2025-09-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_room_created_at_room_updated_at_alter_room_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('delux', 'Delux'), ('double delux', 'Double Delux')], max_length=50),
        ),
    ]
