# Generated by Django 5.1.3 on 2025-09-15 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='maxGuests',
            new_name='max_guests',
        ),
    ]
