# Generated by Django 5.1.3 on 2025-09-15 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_rename_maxguests_room_max_guests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.URLField(default=list),
        ),
    ]
