# Generated by Django 5.2.6 on 2026-02-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_alter_room_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='room',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='room',
            name='images',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('villa', 'Villa'), ('apartment', 'Apartment'), ('suite', 'Suite')], max_length=50),
        ),
    ]
