# Generated by GitHub Copilot on 2026-05-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_room_created_at_remove_room_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('license', 'License'), ('permit', 'Permit'), ('insurance', 'Insurance'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring-soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('reminder_days', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='rooms.room')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
