# Generated by Django 5.2.7 on 2026-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0008_propertydocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="amenities",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name="room",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="room",
            name="images",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
