# Generated by Django 5.2.6 on 2026-05-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_alter_room_amenities_alter_room_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(db_index=True, max_length=255)),
                ('image_url', models.TextField()),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyLevelDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(db_index=True, max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('license', 'License'), ('permit', 'Permit'), ('insurance', 'Insurance'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.TextField()),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expiring-soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed')], default='active', max_length=20)),
                ('reminder_days', models.IntegerField(default=30)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
