# Generated by Django 5.2.6 on 2026-05-29 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings_app', '0003_rentschedule_tenant_user_tenantassignment_and_more'),
        ('rooms', '0010_propertyimage_propertyleveldocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='propertydocument',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='property_documents', to='bookings_app.tenantassignment'),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='property_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='propertydocument',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='property_documents', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expiring-soon', 'Expiring Soon'), ('expired', 'Expired'), ('renewed', 'Renewed'), ('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='type',
            field=models.CharField(choices=[('license', 'License'), ('permit', 'Permit'), ('insurance', 'Insurance'), ('contract', 'Contract'), ('certificate', 'Certificate'), ('id', 'ID Document'), ('proof_of_address', 'Proof of Address'), ('reference', 'Reference Letter'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='BookingInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('message', models.TextField(blank=True, default='')),
                ('property_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('closed', 'Closed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interests', to='rooms.room')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('id', 'ID Document'), ('proof_of_address', 'Proof of Address'), ('contract', 'Tenancy Contract'), ('reference', 'Reference Letter'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('file_url', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, default='')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_documents', to='bookings_app.tenantassignment')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
