# Generated by Django 5.2.6 on 2026-05-29 13:56

from django.db import migrations


def migrate_data(apps, schema_editor):
    PropertyDocument = apps.get_model('rooms', 'PropertyDocument')
    PropertyLevelDocument = apps.get_model('rooms', 'PropertyLevelDocument')
    TenantDocument = apps.get_model('rooms', 'TenantDocument')

    # 1. Update existing PropertyDocument property_id
    for doc in PropertyDocument.objects.all():
        if doc.room and doc.room.location:
            doc.property_id = doc.room.location
            doc.save()

    # 2. Copy PropertyLevelDocument to PropertyDocument
    for doc in PropertyLevelDocument.objects.all():
        new_doc = PropertyDocument.objects.create(
            property_id=doc.property_name,
            name=doc.name,
            type=doc.type,
            description=doc.description,
            file_url=doc.file_url,
            expiry_date=doc.expiry_date,
            renewal_date=doc.renewal_date,
            status=doc.status,
            reminder_days=doc.reminder_days,
            notes=doc.notes,
        )
        if doc.upload_date:
            PropertyDocument.objects.filter(pk=new_doc.pk).update(upload_date=doc.upload_date)

    # 3. Copy TenantDocument to PropertyDocument
    for doc in TenantDocument.objects.all():
        prop_id = ""
        room = None
        if doc.assignment and doc.assignment.room:
            room = doc.assignment.room
            prop_id = room.location or ""

        new_doc = PropertyDocument.objects.create(
            property_id=prop_id,
            room=room,
            tenant=doc.tenant,
            assignment=doc.assignment,
            name=doc.name,
            type=doc.type,
            description=doc.description,
            file_url=doc.file_url,
            status=doc.status,
            admin_notes=doc.admin_notes,
            reviewed_at=doc.reviewed_at,
            uploaded_by=doc.tenant,
        )
        if doc.uploaded_at:
            PropertyDocument.objects.filter(pk=new_doc.pk).update(upload_date=doc.uploaded_at.date())


def rollback_data(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0011_propertydocument_admin_notes_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_data, rollback_data),
    ]

