# Generated by Django 5.2.6 on 2026-05-29 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0012_migrate_document_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyLevelDocument',
        ),
        migrations.AlterField(
            model_name='propertydocument',
            name='property_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='TenantDocument',
        ),
    ]
