# Generated by Django 5.2.6 on 2026-05-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('tenant', 'Tenant'), ('admin', 'Admin')], default='customer', max_length=20),
        ),
    ]
